version: '2'
services:
  web:
    build: .
    command: node /usr/app/src/app.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://apps@postgres/app
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: apps
      POSTGRES_DB: app
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
